# Generated by Django 4.1.7 on 2023-03-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('member_since', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date_of_birth', models.IntegerField()),
            ],
        ),
    ]
