# Generated by Django 4.1.7 on 2023-03-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_author_nationality_remove_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rented_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='renter', to='api.customer'),
        ),
    ]
