# Generated by Django 4.1.7 on 2023-03-16 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_book_rented_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('headquarters', models.CharField(max_length=100)),
                ('founding_year', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='rented_by',
        ),
        migrations.AddField(
            model_name='book',
            name='releasing_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing_house',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='api.publishinghouse'),
        ),
    ]
