# Generated by Django 4.1.7 on 2023-03-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_publishinghouse_remove_book_rented_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishing_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='api.publishinghouse'),
        ),
    ]
