# Generated by Django 4.1.7 on 2023-03-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_book_author_bookswithauthors_book_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BooksWithAuthors',
            new_name='BookWithAuthors',
        ),
    ]
