# Generated by Django 4.1.7 on 2023-03-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_bookswithauthors_bookwithauthors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
