# Generated by Django 4.1.7 on 2023-04-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookwithauthors',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author'),
        ),
        migrations.AlterField(
            model_name='bookwithauthors',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='api.book'),
        ),
    ]
